Output error messages to `stderr`

diff --git a/deb2tgz b/deb2tgz
--- a/deb2tgz
+++ b/deb2tgz
@@ -23,14 +23,16 @@
 CURRDIR=$(pwd)
 
 if [ "$1" = "" ]; then
-    echo "$0:  Converts DEB format to standard GNU tar + (GZ/XZ/LZ/BZ) format."
-    echo "    (view converted packages with \"less\", install and remove"
-    echo "    with \"installpkg\", \"removepkg\", \"pkgtool\", or manually"
-    echo "    with \"tar\")"
-    echo
-    echo "Usage:    $0 <file.deb>"
-    echo "    (Outputs \"file.t*z\")"
-    exit 1;
+    cat - 1>&2 <<EOH
+$0:  Converts DEB format to standard GNU tar + (GZ/XZ/LZ/BZ) format.
+    (view converted packages with "less", install and remove
+    with "installpkg", "removepkg", "pkgtool", or manually
+    with "tar")
+
+Usage:    $0 <file.deb>
+    (Outputs "file.t*z")
+EOH
+    exit 1
 fi
 
 # Create a new temporary directory with a secure filename:
@@ -53,9 +55,9 @@ make_temp_dir()
     if [ -d $tempd ]; then # success, return the name of the directory:
         echo $tempd
     else
-        echo "ERROR:  Could not find mcookie, openssl, or md5."
-        echo "        Exiting since a secure temporary directory could not be made."
-       exit 1
+        echo "ERROR:  Could not find mcookie, openssl, or md5." 1>&2
+        echo "        Exiting since a secure temporary directory could not be made." 1>&2
+        exit 1
     fi
 }
 
@@ -109,7 +111,7 @@ for debfile in $* ; do
           rm "$TMPDIR/data.tar.zst"
 
        else
-         echo "ERROR:  unsupported compression format used inside DEB file ($(basename "$TMPDIR"/data.tar.*))."
+         echo "ERROR:  unsupported compression format used inside DEB file ($(basename "$TMPDIR"/data.tar.*))."  1>&2
          exit 1
 
        fi
